# Logo Url
# Please enter an absolute path to your logo file
# or remove the following line with replacing logo-header.png with your own logo
logo:
  # url: http://www.your-site.com/logo.gif
  # width: 300px
  # height: 50px
# Header
menu:
  Home: /
  # Delete this row if you don't want categories in your header nav bar
  Categories:
  About: /about/
  Tools: /tools/

# Article list grouped by year
groupByYear: true

# Content
fancybox: true

# Thumbnail
thumbnail: false

# Scroll Loading
scrollLoading: true

# Sidebar
sidebar: right # sidebar's position (left or right)
social_links:
  twitter: https://twitter.com/martinrcotta
  facebook: https://www.facebook.com/martin.nearsoft
  google-plus: https://plus.google.com/+MartinCottaNearsoft
  github: https://github.com/martin-cotta
  # weibo:
  # rss:
widgets:
- recent_posts
- category
- archive
- tag
- tagcloud
- links

# Links
links:
  Hexo: http://hexo.io

# Don't Use Google APIs if you are in google-blocked areas
use_google_apis: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
fb_admins:
fb_app_id:
